### ISSUE TITLE
自定义好友列表的一些问题

### ISSUE THREAD

**Issue by hloong** [huangfangyi/FanXin3.0#12]
如果好友列表我从自己的服务器获取，自定义自己的好友列表，那么侧边栏的a-z的东西是不是要自己重写
EaseUser这个map类我这里就不能用了？
因为我好友列表里的数据是比较多的，并不是像EaseUser这么少，或者是我继承EaseUser？但是我的adapter也要重写，无法匹配EaseContactAdapter，或者是我重新继承EaseContactAdapter？
不知道各位遇到过这种没？

**Comment by LijieSong** [comment]
你可以直接修改EaseUser里面的的属性,然后修改你item里面的布局就OK了.那个MAP类应该可以用的啊.
